name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2
    -
      name: Set up docker
      uses: docker/setup-buildx-action@v2
    - 
      name: Login Docker Hub
      uses: docker/login-actions@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - 
      name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME }}/cimipagina:latest
        file: .Dockerfile
    
